id: 093a991fe6354051a0d39c1649f95745
initial_creation_type: ebook
created_at: 24/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །བླ་མ་ལྔ་བཅུ་པའི་རྣམ་བཤད་སློབ་མའི་རེ་བ་ཀུན་སྐོང་ཞེས་བྱ་བ་བཞུགས་སོ།།
  subtitle: ''
  authors:
  - རྗེ་བཙུན་ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
  collection: Tsadra Geluk Series
  publisher: Tsadra Publishing
  id: TSD-GS-06
  cover: tmp5amktqsj.jpg
  credit: tmpgmziuc6n.jpg
